### ISSUE TITLE
Escaping backslashes proliferate

### ISSUE THREAD

**Issue by milupo** [Lusito/web-ext-translator#1]
Hi Lusito,

there is a phenomenon with WET: After saving strings with backslashes which escape other characters - e. g. " or * - the backslashes proliferate. So 3 backslashes shown in WET will be 9! in the saved messages.json - see strings tutorial_page and changelog_page in Forget Me Not extension. What's the causer? WET, messages.json, or the text editor I edit the messages.json with?

Thanks and regards,
Michael

**Comment by Lusito** [comment]
Hi Milupo. Which version are you using? I thought I fixed this bug a while ago.

**Comment by milupo** [comment]
Hi Lusito, 

thank you for the quick reply. I'm using version 1.0.5. I don't know another version.

**Comment by Lusito** [comment]
You can either use NPM:
https://www.npmjs.com/package/web-ext-translator

Or download it from here:
http://lusito.info/web-ext-translator.jar

If you have a file that is dirty (i.e. contains more slashes than it should) from older versions, try editing it in the latest wet version and re-saving it.

**Comment by milupo** [comment]
Where can I see which version I have? The version should be visible (or to be found) on the GUI.

**Comment by Lusito** [comment]
Sorry, that's currently not visible to the user at all. I will change that once I get to working on it again.

**Comment by Lusito** [comment]
I think this should be fixed by now.. if not, please re-open.
