### ISSUE TITLE
Comments JSON files

### ISSUE THREAD

**Issue by rugk** [Lusito/web-ext-translator#10]
> WET helps reduce git changes and thus merge conflicts:
> It automatically formats your messages.json into a homogeneous format.
> The order of the translations in the messages.json is kept

Mhh, this does not sound as if it's what i want. Because other translation platforms also noticed, they do not support comments in JSON files: https://github.com/WeblateOrg/weblate/issues/2043

Similarly, I'd like to keep empty lines and such formatting: https://github.com/WeblateOrg/weblate/issues/2066
It has a reason why I format it like this, so…

**Comment by milupo** [comment]
AFAIK comments can be simulated in messages,json by "description":

localization_key {
"message": "This is the message to be translated.",
"description": "This is a comment."
}

**Comment by rugk** [comment]
Please read https://github.com/WeblateOrg/weblate/issues/2043. WebExtensions actually support real comments via `//`. I'm still surprised this is a so less-known feature.

Actually, you may use it for your hashes or groups instead of real data entries.

**Comment by Lusito** [comment]
I will take a look at this. Thanks.

This is probably less known, because JSON is a standard and JSON doesn't support comments. People tend to not read up on standards they already know.

**Comment by Lusito** [comment]
It looks like the only thing you use comments for are what I added groups for. Am I wrong?
These comments would currently not show up in the editor at all.

**Comment by Lusito** [comment]
Keeping the formatting would be really ugly, since I'd have to basically remember where everything was in the original and then inject it there. The best thing I can do for your formatting would be to allow extension developers to configure how the formatting should look like.

**Comment by rugk** [comment]
> It looks like the only thing you use comments for are what I added groups for. 

yeah, taht's what I use them for, but of course anybody can do anything.

**Comment by Lusito** [comment]
Solved. Try it: https://lusito.github.io/web-ext-translator/?gh=https://github.com/rugk/offline-qr-code

See the [project readme](https://github.com/Lusito/web-ext-translator/blob/master/README.md) for more information on formatting options.

**Comment by rugk** [comment]
Oh, great you added comment support. Not sure though, whether they are always used as group headings, but it seems the logical thing to do.

**Comment by Lusito** [comment]
Will consider that once an actual need arises. Let's see first how people use it.. most extensions I've seen so far don't use comments at all.
