### ISSUE TITLE
Remind users to export the results

### ISSUE THREAD

**Issue by rugk** [Lusito/web-ext-translator#12]
When users are accustomed to other translation services, they may make the mistake and think it is automatically submitted online when they edit the strings.

As that is not the case here, there should be a reminder that it needs to be exported and a Pull Request needs to be made.

**Comment by Lusito** [comment]
Yep, that would be a good thing to have.

**Comment by rugk** [comment]
…maybe also in the sidebar… https://github.com/Lusito/web-ext-translator/issues/11#issuecomment-405094458

**Comment by Lusito** [comment]
Should be solved both in the browser and the standalone version.
