### ISSUE TITLE
"Submit as Pull Request" button

### ISSUE THREAD

**Issue by rugk** [Lusito/web-ext-translator#13]
It would be great, if you could make it easier to contribute the changed strings back to the project. As such, a button "Open PR at repo" or so would be nice.
Just use GitHub's API for that.

I see that OAuth and stuff won't work in a client/JS-only environment, but maybe you can ask a user to manually copy a "personal access token" into the app and use it? (and save in local storage or so)

And at the end either do it automatically or do something with linking users to the "new PR" site.

**Comment by Lusito** [comment]
That would be really awesome to have, but the best thing I have come up with so far is to show a link to the "new issue" and a button which copies some text including the messages.json into the clipboard, so users can just paste it and submit.

Manually entering an access token and storing it in local storage seems to raise security questions, so I'd rather avoid this.
