### ISSUE TITLE
Add new keys directly from wet

### ISSUE THREAD

**Issue by ElectronicManuel** [Lusito/web-ext-translator#21]
Hey,

I'm beginning to translate my extension and I thought it'd be nice if we could add new translation keys directly from wet similar to how we can add new languages.
Currently I have to close wet, add the keys manually and open wet again.

**Comment by Lusito** [comment]
Yes, I've had it in the old version, but when I rewrote this from scratch I wanted to focus a bit more on the translator part and translators shouldn't be able to add new lines.
But I will re-add this for the standalone version you can install via npm.

**Comment by Lusito** [comment]
It's possible now using the standalone version
