### ISSUE TITLE
QUESTION: Any chance for a more general translator?

### ISSUE THREAD

**Issue by JakubKoralewski** [Lusito/web-ext-translator#29]
So that you could choose any source file, any target language file and edit those. 

For example if it worked with vue-i18n, this is how my setup looks: https://github.com/JakubKoralewski/dziennik_php_frontend/tree/f94c9eb12a6422713b3a8c74f669700de9dc50ba/src/locales/messages

**Comment by Lusito** [comment]
Sorry, but that is out of scope for this project. You are welcome to fork it and rewrite it so that it works for your use-case.
