### ISSUE TITLE
Honor original file or editorconfig file for indentation in JSON

### ISSUE THREAD

**Issue by rugk** [Lusito/web-ext-translator#30]
In the export you get when coping you seem to use 4 spaces for indentation.

This is bad, because:
* I use 2 spaces indentation in my project ([and at least in NodeJS that seem to be the standard](https://stackoverflow.com/questions/18698738/what-is-the-json-indentation-level-convention))
* it thus breaks diffs

So:
* possibly use the original indentation from the files
* honor the https://editorconfig.org/ file, which may also has this set

**Comment by Lusito** [comment]
Thanks for the report. I'm not going to include support for editorconfig, but I'll look into solving this issue.

**Comment by rugk** [comment]
Well… editorconfig would be easier than anything else, I guess. :wink: [This is supported by the GitHub online edtor, too.](https://github.com/isaacs/github/issues/170#issuecomment-150489692) But AFAIK, it also tries to auto-detect the indentation and falls back to this, if this is done.

**Comment by rugk** [comment]
If this is supposed to be a "good first issue", it would be good to know the exact steps/requirements to solve the problem. Currently, it's just a problem description… :thinking: (not even has editorconfig thing be decided)

**Comment by rugk** [comment]
Any news?

**Comment by Lusito** [comment]
Nope, sorry, too busy with other stuff at the moment. Feel free to create a pull request. Be it editorconfig or otherwise. As long as the behavior doesn't change for people without editorconfig.

**Comment by hensm** [comment]
Would you still accept a PR for this?

**Comment by Lusito** [comment]
Sure. PRs are always welcome.

**Comment by Lusito** [comment]
Solved with version 3.0. Thanks @hensm
