### ISSUE TITLE
Text direction rtl (right-to-left language)

### ISSUE THREAD

**Issue by shanirub** [Lusito/web-ext-translator#31]
When trying to combine english lettters in an hebrew translation, word order gets mixed up.

To correct this, an extra css property should be added to all relevant text fields:
`direction: rtl`
This property should probably be applied to all text fields when translating to/from another rtl language.

**Comment by Lusito** [comment]
Thanks for the report. A fix has been deployed. I've taken this list as reference to see which locales are RTL:
https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code

If you think that list is incomplete, please notify me.
