### ISSUE TITLE
[enhancement] mark finished lines by dimming or color

### ISSUE THREAD

**Issue by perdolka** [Lusito/web-ext-translator#4]
<a href="http://piccy.info/view3/12414706/e790e697f319edf0245a1ecf1e99a803/orig/" target="_blank"><img src="http://i.piccy.info/i9/7ec294ab8cb43a1812fc23f4d2ded40d/1529017630/88588/1246306/sshot_188_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-06-14-23-07/i9-12414706/778x549-r" target="_blank"><img src="http://i.piccy.info/a3/2018-06-14-23-07/i9-12414706/778x549-r/i.gif" alt="" border="0" /></a>

**Comment by Lusito** [comment]
I'm currently rewriting the entire thing to be web-based and this feature is already in the works.

**Comment by Lusito** [comment]
Also interesting for you @milupo:

I've implemented a red line at the right side of the textarea when the original language has been changed.

You can see this red line when:
- You edit the original language's message in the editor
- The extension author edited the original language's message and the other language has already been saved before with this editor.
- When loading an extension, which has not yet been used with this editor, the editor assumes, that all messages are up to date.

Once you change the textarea of the message which is out of date, the red line will disappear.

I'm open to suggestions how to visually distinguish the changed lines/editors even more. I've tried dimming them, but it makes things harder to read if you want to change translations for non-changed entries.
