### ISSUE TITLE
Unable to input line breaks

### ISSUE THREAD

**Issue by radradix** [Lusito/web-ext-translator#45]
When trying to create a translation of a web extension (Forget Me Not, as it happens), I was unable to insert line breaks either by hitting Enter or by copy-pasting in from an external notes application. Am I missing something? 

For example, the original was shown on the left like so (redacted for simplicity):
```
- **N**ever: No cleanup. 
- On **S**tartup
```
It appeared like one would expect, interpreted through Markdown. In contrast, when I tried to create a translation in the right side, it looked like: 
```
- **N**unca.-Empezar**S**e: Limpiar cuando el navegador se empieze.
```

(Lusito: Thank you for creating this! It truly is helpful.)

**Comment by Lusito** [comment]
Thanks for the report. Sorry about the delay. Sometimes I miss the notifications.
The problem was only on firefox. I've changed the code to a different solution for the editor, which fixes the problem. I just hope it doesn't introduce new problems.
