### ISSUE TITLE
Also check for main branch

### ISSUE THREAD

**Issue by rugk** [Lusito/web-ext-translator#82]
AFAIK by default it only checks for a branch named "master" when loading a repository by just giving a repository API.

IMHO, it should also check for "main", which,y b now – is quite the default nowadays.

ref https://github.com/rugk/mastodon-simplified-federation/pull/118#discussion_r1348714063

**Comment by Lusito** [comment]
Thanks for the report. If the branch is not specified, it will now fetch the default branch from the API.
